# -*- coding: utf-8 -*-
"""Voice_clone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJs-RvEYZzyi4UcMYzLQbft-NwMp69Ic
"""

# app.py
import streamlit as st
from TTS.api import TTS
import os

# Set Streamlit page config
st.set_page_config(page_title="🗣️ Clone Voice TTS", layout="centered")
st.title("🗣️ Text-to-Speech Using Your Voice")
st.markdown("Upload a sample of your voice (WAV) and enter any text to hear it spoken in your voice!")

# Load TTS model
@st.cache_resource
def load_tts_model():
    return TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=False)

tts = load_tts_model()

# Upload voice sample
speaker_file = st.file_uploader("🎤 Upload your voice sample (.wav)", type=["wav"])

# Text input
text_input = st.text_area("💬 Enter text to speak", placeholder="Type something like: Hello, how are you?")

# Button to generate speech
if st.button("🧠 Generate Voice"):
    if not speaker_file:
        st.error("Please upload a voice sample!")
    elif not text_input.strip():
        st.error("Please enter some text!")
    else:
        with st.spinner("Synthesizing speech..."):
            # Save uploaded file
            speaker_wav_path = "uploaded_voice.wav"
            with open(speaker_wav_path, "wb") as f:
                f.write(speaker_file.read())

            # Output path
            output_path = "cloned_output.wav"

            # Run TTS
            tts.tts_to_file(
                text=text_input,
                speaker_wav=speaker_wav_path,
                file_path=output_path,
                language="en"
            )

            # Playback
            st.success("✅ Speech generated!")
            st.audio(output_path)

